### ISSUE TITLE
My Review: Fun game, nice mechanics, easier than 2048.

### ISSUE THREAD

**Issue by a-raccoon** [mattvchandler/2050#2]
My first game was fun but also generally easy. The mechanics are nice to look at and interact with.  I do have a few suggestions.

* Make the gameplay area full screen. It would be visually pleasing and a rectangular play field (16:9 or 16:10) shouldn't alter gameplay too significantly.  The pressure bar can use a top sliver of the screen, and eliminate the compass.

* increase and decrease difficulty of a game session by increasing the balls size by a factor multiplier.  When you win a game, the factor increases. When you lose, the factor decreases.  Perhaps based on points and overall high score. Weighted.

* Allow for finger sliding in addition to swiping. When you hold your finger down, a new ball will appear every 0.25 or 2.0 seconds (depending on pressure). The direction you last slid your finger is the direction of gravity.  You can do two modes; direction of finger from screen center, or relative from last drag (of 5 or 10 pixels).

That's all I have. Fun games. Will play it bunches more!

![Screen Capture] (http://i.imgur.com/gGdVOLv.jpg)

**Comment by mattvchandler** [comment]
Thanks for the feedback, I'm glad you enjoyed it.

I don't want to mess with the difficulty balance right now. Changing to fullscreen would nearly double the play area, which would make the game considerably easier.

I don't like the idea of automatically changing the difficulty by changing ball sizing, but that might work as an option in the settings menu. That would make it opt-in vs punishing success.

I think 'finger sliding' could work pretty well. If I get some time I'll look into this one, but it could be a while.

You're welcome to fork and try out some of these ideas. If you can get it working without breaking the balance, submit a PR.

If you're looking for a greater challenge, try to get to 4096. It's possible, but requires a lot more planning than getting to 2048. It may even be possible to get to 8192, but I haven't been able to prove one way or another yet. You could also challenge the high score. Mine is currently 50296.
